"""updated the database with new DeliveryCompartments table and modified Delivery table. Completed Admin and Driver constructors.

Revision ID: 186364ba64a5
Revises: cba6cfdddbc1
Create Date: 2023-05-17 07:46:08.036541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '186364ba64a5'
down_revision = 'cba6cfdddbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(length=20), nullable=True))

    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.drop_column('petrol')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filled', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('available', sa.Integer(), nullable=False))
        batch_op.drop_constraint('delivery_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('delivery_ibfk_3', type_='foreignkey')
        batch_op.drop_column('address_id')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('delivery_compartments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=False))
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('petrol',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('delivery_compartments', schema=None) as batch_op:
        batch_op.alter_column('petrol',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('qty')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('delivery_ibfk_3', 'address', ['address_id'], ['id'])
        batch_op.create_foreign_key('delivery_ibfk_1', 'order', ['order_id'], ['id'])
        batch_op.drop_column('available')
        batch_op.drop_column('filled')

    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('petrol', mysql.VARCHAR(length=6), nullable=True))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('group')

    # ### end Alembic commands ###
