"""updated order table

Revision ID: 6817ab036931
Revises: 
Create Date: 2023-05-13 21:27:47.368191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6817ab036931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('delivery_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('q_diesel',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('q_87',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('q_90',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('q_ulsd',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('q_ulsd',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('q_90',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('q_87',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('q_diesel',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('delivery_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('order_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
