"""Added parish column to Delivery table

Revision ID: 71355f1381c8
Revises: 680717c23f59
Create Date: 2023-05-14 20:02:46.916690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71355f1381c8'
down_revision = '680717c23f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parish', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('parish')

    # ### end Alembic commands ###
