"""updated order table a second time

Revision ID: 717bc6ec3a62
Revises: 6817ab036931
Create Date: 2023-05-13 21:35:00.315308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717bc6ec3a62'
down_revision = '6817ab036931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
