"""Updated compartments table

Revision ID: 7a8a0e5cb4f2
Revises: c9cf27b5fbe2
Create Date: 2023-05-15 05:36:40.774528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8a0e5cb4f2'
down_revision = 'c9cf27b5fbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.drop_constraint('compartments_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.create_foreign_key('compartments_ibfk_2', 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###
