"""Added petrol table to Compartments

Revision ID: c9cf27b5fbe2
Revises: ccb346611f40
Create Date: 2023-05-15 03:50:26.769903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cf27b5fbe2'
down_revision = 'ccb346611f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petrol', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.drop_column('petrol')

    # ### end Alembic commands ###
