"""Added date and time columns to Delivery table and changed booked column to active in Trucks table

Revision ID: ccb346611f40
Revises: 71355f1381c8
Create Date: 2023-05-14 21:28:13.857217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccb346611f40'
down_revision = '71355f1381c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('time', sa.String(length=20), nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('delivery_time',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('booked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('active')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('delivery_time',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
