"""updated order table

Revision ID: cd3c2c783f99
Revises: 717bc6ec3a62
Create Date: 2023-05-14 01:02:30.402987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd3c2c783f99'
down_revision = '717bc6ec3a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('delivery_time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('delivery_time',
               existing_type=sa.String(length=80),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('delivery_date',
               existing_type=sa.String(length=80),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
