"""Increased string size for petrol

Revision ID: deebfcf4abf1
Revises: 7a8a0e5cb4f2
Create Date: 2023-05-16 01:24:23.329403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deebfcf4abf1'
down_revision = '7a8a0e5cb4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.alter_column('petrol',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compartments', schema=None) as batch_op:
        batch_op.alter_column('petrol',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
